language: node_js

services:
  - couchdb

node_js:
  - "14"
sudo: false
script: npm run $COMMAND
before_script:
  - curl -X PUT localhost:5984/test

env:
  matrix:
  - COMMAND=test
  - CLIENT=selenium:phantomjs COMMAND=test
  - COMMAND=coverage

branches:
  only:
  - master
